### ISSUE TITLE
Application does not launch?

### ISSUE THREAD

**Issue by sjrc6** [deanthecoder/GLSLShaderShrinker#2]
I would really like to try this but I can't get it to open after it's installed. I'm not sure why.

Ive tried:
release alpha v0.7
release alpha v0.6
Full system restart
Running as administrator

I'm on windows 10, ryzen 5600x, rtx 3070

**Comment by deanthecoder** [comment]
Hi Tater,

Sorry about that - I have just seen a similar problem when installing on a 'clean' Windows machine.
And thanks very much for taking the time to report the issue.

Would you mind trying the latest installer?
https://github.com/deanthecoder/GLSLShaderShrinker/releases/tag/Release_0_8_0_0

When running the app, you might see a prompt to install the Microsoft .Net 5.0 runtimes if you don't already have them.

Fingers crossed!

**Comment by sjrc6** [comment]
Success! That seems to have fixed it. I didn't see any prompt to install .Net 5.0 but it worked regardless.

**Comment by deanthecoder** [comment]
Excellent! Thanks very much for giving it another try!

**Comment by deanthecoder** [comment]
Hi Tater - I've just realised v0.8.0.0 was actually based on quite an old code base. I've just uploaded a new installer with many more features and bug fixes.

**Comment by sjrc6** [comment]
Thanks for letting me know, I will install the new version.
